- name: gcr.io/$PROJECT_ID/sonar-scanner:latest
  args:
    - '-Dsonar.host.url=35.201.181.7'
    - '-Dsonar.login=12e04faac0567120d725d4bc493976c4cf440471'
    - '-Dsonar.projectKey=sonar-git'
    - '-Dsonar.sources=.'
